name: islamic_app_saudi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  audioplayers: ^6.1.0
  geolocator: 11.1.0
  adhan: ^2.0.0+1
  flutter_local_notifications: ^17.2.2
  permission_handler:
  timezone: ^0.9.0
  device_info_plus: ^9.0.0
  shared_preferences: ^2.0.18
  flutter_background: ^1.3.0+1
  file_picker: ^5.0.0
  flutter_screenutil: ^5.9.3
  wakelock_plus: ^1.2.8
  flutter_native_splash: ^2.4.3
  flutter_launcher_icons:
  video_player: ^2.9.2
  youtube_player_flutter: ^9.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#002B25" # اللون الخلفي للشاشة
  image: "assets/images/icon.png"
  android: true # تمكين الدعم لنظام أندرويد
  ios: true # تمكين الدعم لنظام iOS
  android_12:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"
  image_path_ios: "assets/images/icon.png"  # استخدام نفس الأيقونة للـ iOS


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/subhan_allah.mp3
    - assets/sound/la_ilah_illa_allah.mp3
    - assets/sound/alhamdulillah.mp3
    - assets/sound/allahumma_salli_ala_nabiyina.mp3
    - assets/sound/astaghfirullah_wa_atubu.mp3
    - assets/sound/hasbuna_allah_wa_ni3ma.mp3
    - assets/sound/la_hawla_wala_quwata_elali_elazem.mp3
    - assets/sound/la_ilaha_illa_allah_wahdh_la.mp3
    - assets/sound/la_ilaha_illa_anta.mp3
    - assets/sound/salat_ala_mohammad.mp3
    - assets/sound/subhan_alaah_wbhmd_sobhan_alaah.mp3
    - assets/sound/subhan_allah_wa_bihamdih.mp3

  fonts:
    - family: messiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 700
