name: islamic_app_saudi
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  audioplayers: ^6.1.0
  geolocator: 11.1.0
  adhan: ^2.0.0+1
  flutter_local_notifications: ^17.2.2
  permission_handler:
  timezone: ^0.9.0
  device_info_plus: ^9.0.0
  shared_preferences: ^2.0.18
  flutter_background: ^1.3.0+1
  file_picker: ^5.0.0
  flutter_screenutil: ^5.9.3
  wakelock_plus: ^1.2.8
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#42a5f5" # اللون الخلفي للشاشة
  image: assets/images/icon_splash.png # مسار صورة الشاشة
  android: true # تمكين الدعم لنظام أندرويد
  ios: true # تمكين الدعم لنظام iOS
  web: false # تعطيل الدعم للويب (يمكن تغييره إذا لزم الأمر)
  android_12:

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/subhan_allah.mp3
    - assets/sound/la_ilah_illa_allah.mp3
    - assets/sound/alhamdulillah.mp3

  fonts:
    - family: messiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 700
